@extends('layouts.social')
@section('title','Home · Connectly')
@section('content')
<div class="grid grid-cols-1 lg:grid-cols-[230px_minmax(0,680px)_260px] gap-6 justify-center">
<aside class="hidden lg:block"><div class="card p-4 sticky top-24 space-y-1"><div class="flex items-center gap-3 p-3 mb-2"><div class="avatar">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</div><div><div class="font-bold text-sm">{{ auth()->user()->name }}</div><div class="text-xs text-slate-500">Your profile</div></div></div><a class="side-link" href="{{ route('profile',auth()->user()) }}">👤 Profile</a><a class="side-link relative" href="{{ route('friends.index') }}">👥 Friends @if(($friendRequestCount ?? auth()->user()->receivedFriendships()->where('status','pending')->count()))<span class="float-right bg-red-500 text-white rounded-full text-[10px] px-1.5 py-0.5">{{ $friendRequestCount ?? auth()->user()->receivedFriendships()->where('status','pending')->count() }}</span>@endif</a><a class="side-link" href="{{ route('saved.index') }}">🔖 Saved posts</a><a class="side-link" href="{{ route('notifications.index') }}">🔔 Notifications</a></div></aside>
<section class="space-y-5">
<div class="rounded-3xl p-6 text-white bg-gradient-to-br from-blue-600 via-indigo-600 to-violet-700 shadow-lg"><div class="text-sm opacity-80">WELCOME BACK</div><h1 class="text-2xl font-black mt-1">Connect. Share. Discover.</h1><p class="mt-2 text-sm text-white/80">Share your thoughts and stay connected with your community.</p></div>
<div class="card p-4"><div class="flex gap-3"><div class="avatar">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</div><button onclick="openCreatePost()" class="flex-1 text-left bg-slate-100 hover:bg-slate-200 rounded-2xl px-5 py-3 text-slate-500 transition">What's on your mind, {{ Str::before(auth()->user()->name,' ') }}?</button></div><div class="grid grid-cols-3 mt-4 border-t pt-3 text-sm font-semibold"><button onclick="openCreatePost()">📝 Post</button><button onclick="openCreatePost()">📷 Photo</button><a class="text-center" href="{{ route('friends.index') }}">👥 Find people</a></div></div>
@forelse($posts as $post)
<article class="card overflow-hidden">
<div class="p-4 flex items-center gap-3"><a href="{{ route('profile',$post->user) }}" class="avatar">{{ strtoupper(substr($post->user->name,0,1)) }}</a><div class="flex-1"><a class="font-bold hover:text-blue-600" href="{{ route('profile',$post->user) }}">{{ $post->user->name }}</a><div class="text-xs text-slate-500">{{ $post->created_at->diffForHumans() }} · {{ ucfirst(str_replace('_',' ',$post->privacy)) }}</div></div>
@if($post->user_id===auth()->id())<div class="relative"><button type="button" onclick="togglePostMenu({{ $post->id }})" class="w-9 h-9 rounded-full hover:bg-slate-100 text-slate-500 font-bold">•••</button><div id="post-menu-{{ $post->id }}" class="hidden absolute right-0 top-10 z-20 w-36 bg-white border rounded-xl shadow-lg overflow-hidden"><button type="button" onclick="openEditPost({{ $post->id }})" class="w-full text-left px-4 py-3 text-sm hover:bg-slate-50">✏️ Edit post</button><form method="POST" action="{{ route('posts.destroy',$post) }}" onsubmit="return confirm('Are you sure you want to delete this post? This action cannot be undone.');">@csrf @method('DELETE')<button class="w-full text-left px-4 py-3 text-sm text-red-600 hover:bg-red-50">🗑 Delete</button></form></div></div>@endif</div>
@if($post->body)<div class="px-4 pb-4 whitespace-pre-line leading-7">{{ $post->body }}</div>@endif @if($post->image)<img src="{{ asset('storage/'.$post->image) }}" class="w-full max-h-[650px] object-cover">@endif
<div class="px-4 py-3 text-sm text-slate-500 flex justify-between border-b"><span>👍 {{ $post->likes_count }} likes</span><span>{{ $post->comments->count() }} comments</span></div>
<div class="grid grid-cols-3 border-b"><form method="POST" action="{{ route('posts.like',$post) }}">@csrf<button class="w-full py-3 font-semibold hover:bg-slate-50">{{ $post->isLikedBy(auth()->user())?'👍 Liked':'👍 Like' }}</button></form><button onclick="document.getElementById('comment-{{ $post->id }}').focus()" class="font-semibold hover:bg-slate-50">💬 Comment</button><form method="POST" action="{{ route('posts.save',$post) }}">@csrf<button class="w-full py-3 font-semibold hover:bg-slate-50">{{ $post->isSavedBy(auth()->user())?'🔖 Saved':'🔖 Save' }}</button></form></div>
<div class="p-4 space-y-3">@foreach($post->comments->take(4) as $comment)<div class="flex gap-2"><div class="w-8 h-8 shrink-0 rounded-full bg-slate-100 flex items-center justify-center text-xs font-bold">{{ strtoupper(substr($comment->user->name,0,1)) }}</div><div class="bg-slate-100 rounded-2xl px-3 py-2 text-sm"><div class="font-semibold">{{ $comment->user->name }}</div><div>{{ $comment->body }}</div></div></div>@endforeach<form method="POST" action="{{ route('comments.store',$post) }}" class="flex gap-2">@csrf<input id="comment-{{ $post->id }}" name="body" required placeholder="Write a comment..." class="flex-1 bg-slate-100 rounded-full px-4 py-2 outline-none"><button class="btn btn-primary">Send</button></form></div>
</article>
@empty<div class="card p-10 text-center"><div class="text-5xl mb-3">🌱</div><h2 class="text-xl font-bold">Your feed is waiting</h2><p class="text-slate-500 mt-2">Create your first post or connect with people.</p></div>@endforelse
{{ $posts->links() }}</section>
<aside class="hidden lg:block"><div class="card p-5 sticky top-24"><div class="flex justify-between items-center mb-4"><h3 class="font-bold">People you may know</h3><a href="{{ route('search') }}" class="text-xs text-blue-600">See all</a></div>@foreach($suggestions as $person)<div class="flex items-center gap-3 py-3 border-b last:border-0"><a class="avatar-sm" href="{{ route('profile',$person) }}">{{ strtoupper(substr($person->name,0,1)) }}</a><div class="flex-1 min-w-0"><a class="font-semibold text-sm truncate block" href="{{ route('profile',$person) }}">{{ $person->name }}</a><div class="text-xs text-slate-500">New to Connectly</div></div><form method="POST" action="{{ route('friends.store',$person) }}">@csrf<button class="text-xs font-bold text-blue-600">Add</button></form></div>@endforeach</div></aside></div>

<div id="post-modal" class="hidden fixed inset-0 z-[60] bg-slate-950/60 p-4 overflow-y-auto"><div class="max-w-lg mx-auto mt-16 bg-white rounded-3xl p-6 shadow-2xl"><div class="flex justify-between items-center mb-5"><h2 class="text-xl font-black">Create post</h2><button onclick="closeCreatePost()" class="text-2xl text-slate-400">×</button></div><form method="POST" action="{{ route('posts.store') }}" enctype="multipart/form-data">@csrf<textarea name="body" rows="5" placeholder="What's on your mind?" class="w-full border-slate-200 rounded-2xl p-4"></textarea><div class="mt-4"><label class="block text-sm font-semibold mb-2">Add a photo</label><input id="create-image" type="file" name="image" accept="image/*" onchange="previewImage(this,'create-preview')" class="text-sm w-full"><img id="create-preview" class="hidden mt-3 w-full max-h-72 object-cover rounded-2xl border" alt="Photo preview"></div><select name="privacy" class="w-full border-slate-200 rounded-xl px-3 py-2 mt-4"><option value="public">🌎 Public</option><option value="friends">👥 Friends</option><option value="only_me">🔒 Only me</option></select><button class="btn btn-primary w-full mt-5">Publish post</button></form></div></div>

@foreach($posts as $post) @if($post->user_id===auth()->id())
<div id="edit-modal-{{ $post->id }}" class="hidden fixed inset-0 z-[61] bg-slate-950/60 p-4 overflow-y-auto"><div class="max-w-lg mx-auto mt-16 bg-white rounded-3xl p-6 shadow-2xl"><div class="flex justify-between items-center mb-5"><h2 class="text-xl font-black">Edit post</h2><button onclick="closeEditPost({{ $post->id }})" class="text-2xl text-slate-400">×</button></div><form method="POST" action="{{ route('posts.update',$post) }}" enctype="multipart/form-data">@csrf @method('PATCH')<textarea name="body" rows="5" class="w-full border-slate-200 rounded-2xl p-4">{{ $post->body }}</textarea>@if($post->image)<img src="{{ asset('storage/'.$post->image) }}" class="mt-3 w-full max-h-64 object-cover rounded-2xl">@endif<input type="file" name="image" accept="image/*" onchange="previewImage(this,'edit-preview-{{ $post->id }}')" class="text-sm w-full mt-4"><img id="edit-preview-{{ $post->id }}" class="hidden mt-3 w-full max-h-64 object-cover rounded-2xl border"><select name="privacy" class="w-full border-slate-200 rounded-xl px-3 py-2 mt-4"><option value="public" @selected($post->privacy==='public')>🌎 Public</option><option value="friends" @selected($post->privacy==='friends')>👥 Friends</option><option value="only_me" @selected($post->privacy==='only_me')>🔒 Only me</option></select><button class="btn btn-primary w-full mt-5">Save changes</button></form></div></div>
@endif @endforeach

<script>
function openCreatePost(){document.getElementById('post-modal').classList.remove('hidden')}
function closeCreatePost(){document.getElementById('post-modal').classList.add('hidden')}
function togglePostMenu(id){document.querySelectorAll('[id^="post-menu-"]').forEach(el=>{if(el.id!=='post-menu-'+id)el.classList.add('hidden')});document.getElementById('post-menu-'+id).classList.toggle('hidden')}
function openEditPost(id){document.getElementById('post-menu-'+id).classList.add('hidden');document.getElementById('edit-modal-'+id).classList.remove('hidden')}
function closeEditPost(id){document.getElementById('edit-modal-'+id).classList.add('hidden')}
function previewImage(input,targetId){const file=input.files&&input.files[0];const img=document.getElementById(targetId);if(!file){img.classList.add('hidden');img.removeAttribute('src');return}if(!file.type.startsWith('image/'))return;const reader=new FileReader();reader.onload=e=>{img.src=e.target.result;img.classList.remove('hidden')};reader.readAsDataURL(file)}
document.addEventListener('click',e=>{if(!e.target.closest('.relative'))document.querySelectorAll('[id^="post-menu-"]').forEach(el=>el.classList.add('hidden'))});
</script>
@endsection
